// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// 背景色をクリックイベントで変更するcontroller
import HighlightController from "./highlight_controller";
application.register("highlight", HighlightController);

// formでイベント処理を行うcontroller
import PostController from "./post_controller";
application.register("post", PostController);

//複数入力のフィールドを動的に追加するcontroller
import AddFieldsController from "./add-fields_controller";
application.register("add-fields", AddFieldsController);

//Railsへ非同期でformを投げるcontroller
import TaskFormController from "./task_form_controller";
application.register("task-form", TaskFormController);

import HelloController from "./hello_controller"
application.register("hello", HelloController)
